[package]
name = "sponge-build"
version = "0.1.0"
edition = "2018"
authors = ["bradinator <imnotamilkglass@gmail.com>"]
description = "A powerful rust module to convert Rust to ASM"
license = "MIT"

[dependencies]
clap = "4.0.0"   # Adjust the version as needed
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "sponge_build"
path = "src/lib.rs"
